### ISSUE TITLE
Ver 0.4.1 uses too much CPU 

### ISSUE THREAD

**Issue by acumenrev** [luosheng/OpenSim#47] opened 2018-11-18 12:35 UTC
Just install new version of OpenSim (v 0.4.1) and I see that it uses too much CPU. You can a look at the image below.

<img width="468" alt="screen shot 2018-11-18 at 7 33 36 pm" src="https://user-images.githubusercontent.com/8485303/48672487-16b73900-eb69-11e8-98c6-c480d1725708.png">

**Comment by Bunn** [comment] 2018-11-19 15:01
@acumenrev does it stays like that forever?
I can't reproduce on my side:
![screen shot 2018-11-19 at 14 57 30](https://user-images.githubusercontent.com/782316/48714995-dc52a800-ec0b-11e8-80ee-9fdece358f91.png)
![screen shot 2018-11-19 at 14 58 17](https://user-images.githubusercontent.com/782316/48714997-dceb3e80-ec0b-11e8-92ae-26d3ab1496ce.png)

What macOS version are you using?
Can you post the output of `xcrun simctl list -j` here?
thanks

**Comment by acumenrev** [comment] 2018-11-20 02:08
@Bunn  yes, it always like that. More than 300. I am using the latest mac os version 10.14.1. What info do you need from me for running `xcrun simctl list -j` ?

**Comment by Bunn** [comment] 2018-11-20 12:56
@acumenrev I'd like to see the entire the json output because it's the only thing I can think of it's different from my situation, which works fine.

**Comment by acumenrev** [comment] 2018-11-20 13:04
@Bunn  here you are https://codebeautify.org/jsonviewer/cbe43b1d

**Comment by Bunn** [comment] 2018-11-21 22:16
@acumenrev I tested with your json output and wasn't able to reproduce on my end as well. Only small CPU usage when opening the app or refreshing the simulator list, as expected.
<img width="257" alt="screen shot 2018-11-21 at 22 16 07" src="https://user-images.githubusercontent.com/782316/48871056-0d350780-eddb-11e8-927e-27bc0ed1fda7.png">

Would it be possible for you to download the project (master branch) on your mac and profile it?

**Comment by acumenrev** [comment] 2018-11-22 06:04
@Bunn  sure, I think I can help

**Comment by acumenrev** [comment] 2018-11-24 02:51
@Bunn hey, I attach my time profiler record, I think we have a problem with calcSize in Application. Don't know it happens to you or not?
[OpenSimProfiler.trace.zip](https://github.com/luosheng/OpenSim/files/2611967/OpenSimProfiler.trace.zip)

**Comment by Bunn** [comment] 2018-11-24 16:09
@acumenrev interesting, this helps a lot. It doesn't happen on my end, I have several apps installed but the biggest one is 150mb, maybe this has something to do with it. OK, I'll see what I can to to improve the performance of the calcSize method. Thanks :)

**Comment by Bunn** [comment] 2018-11-24 17:09
@acumenrev Can you update and give it a try on the develop branch? I've made some changes to use `du` instead of FileManager, and from my tests here it seems that the performance was improved. I just noticed that sometimes the app call the calcSize more times than it's necessary, I'm still taking a look at it, but let me know if the develop branch is working better for you. Thanks

**Comment by acumenrev** [comment] 2018-11-25 00:31
@Bunn it's better than the previous one, but as I observe on Activity Monitor, it always consume more than 20% of CPU. Is that acceptable in your machine ?

[OpenSimProfilerNov25.trace.zip](https://github.com/luosheng/OpenSim/files/2612705/OpenSimProfilerNov25.trace.zip)

**Comment by Bunn** [comment] 2018-11-25 15:09
@acumenrev I'm happy that it got better, but what I don't understand yet are these multiple spikes
<img width="310" alt="screen shot 2018-11-25 at 15 08 58" src="https://user-images.githubusercontent.com/782316/48980672-0997ce00-f0c4-11e8-8043-114321ee37fc.png">

This is only supposed to happen when calculating the size when building the menu or clicking refresh. Did this happen only by opening the app or did you click refresh a bunch of times? Thanks

ps.  What is the spec of your mac? would be interesting to know:
- CPU
- If it's SSD or HD
- macOS version.

**Comment by Bunn** [comment] 2018-11-25 17:59
One thing I notice is that the app has this `DirectoryWatcher` that forces a reload every time there's a change on the /CoreSimulator/Devices folder and subfolders. By any chance do you have any app that could be changing these folders and forcing a reload every 5 seconds or so?
I did increase the delay to avoid multiple reloads from 1 to 5 seconds when it's a folder notification change, and kept the 1 second for user refresh. This is on the develop branch, give it a try and let me know if it improves the situation.

Ideally we could solve this by lazy loading some information only when the user opens the menu, after all, there's no need to keep updating information if the app is not even visible, but I don't want to add a delay for when the user clicks the icon and sees the information. I'll investigate a better solution for this. Meanwhile, let me know if the fix improved and also your mac specs as I mentioned on the previous comment.

Thanks for your help @acumenrev  :)

**Comment by acumenrev** [comment] 2018-11-26 23:26
> @acumenrev I'm happy that it got better, but what I don't understand yet are these multiple spikes
> <img alt="screen shot 2018-11-25 at 15 08 58" width="310" src="https://user-images.githubusercontent.com/782316/48980672-0997ce00-f0c4-11e8-8043-114321ee37fc.png">
> 
> This is only supposed to happen when calculating the size when building the menu or clicking refresh. Did this happen only by opening the app or did you click refresh a bunch of times? Thanks
> 
> ps. What is the spec of your mac? would be interesting to know:
> 
> * CPU
> * If it's SSD or HD
> * macOS version.

I just open the app and do nothing. My MBP 2015 Specs:

CPU: 2.5 Ghz Core i7
500 GB SSD
Mojave 10.14.1

**Comment by acumenrev** [comment] 2018-11-26 23:33
> One thing I notice is that the app has this `DirectoryWatcher` that forces a reload every time there's a change on the /CoreSimulator/Devices folder and subfolders. By any chance do you have any app that could be changing these folders and forcing a reload every 5 seconds or so?
> I did increase the delay to avoid multiple reloads from 1 to 5 seconds when it's a folder notification change, and kept the 1 second for user refresh. This is on the develop branch, give it a try and let me know if it improves the situation.
> 
> Ideally we could solve this by lazy loading some information only when the user opens the menu, after all, there's no need to keep updating information if the app is not even visible, but I don't want to add a delay for when the user clicks the icon and sees the information. I'll investigate a better solution for this. Meanwhile, let me know if the fix improved and also your mac specs as I mentioned on the previous comment.
> 
> Thanks for your help @acumenrev :)

it's perfect now 🙌. The CPU usage often lower than 5%, sometimes it hits 50% but rarely. I truly appreciate it.

Actually, I don't have that kind of app that make changes in Simulator folders/subfolders every 5 seconds

**Comment by Bunn** [comment] 2018-11-28 21:46
Fixed on release[ 0.4.2](https://github.com/luosheng/OpenSim/releases/tag/0.4.2)

**Closed as completed by Bunn** 2018-11-28 21:46 UTC
